# Configuration file for WixMarket

database-initialized: false # DO NOT change, except if you want to reset the database
auto-save: 5 # Time between database saving in seconds, do not change except if you're experiencing problems