main: fr.wixonic.market.Main
api-version: 1.20
version: 1.0.0

author: Wixonic
name: WixMarket
description: Adds a powerful market system in your Minecraft server
website: https://github.com/Wixonic/Market

commands:
    market:
        aliases: mk
        description: Everything about the market
        permission: market

permissions:
    market:
        description: Market access permissions
        default: true
        
    market.buy:
        description: Market buying permissions
        default: true
        children:
            market: true
        
    market.sell:
        description: Allows to sell items in the market
        default: true
        children:
            market: true
        
    market.request:
        description: Allows to create buying and selling requests
        default: true
        children:
            market: true

    market.manage:
        description: Allows to manage the market
        default: op
        children:
            market: true
            market.buy: true
            market.sell: true
            market.request: true