main: fr.wixonic.market.Main
api-version: "1.20"
version: 1.0.0

author: Wixonic
name: WixMarket
description: Adds a powerful market system in your Minecraft server
website: "https://github.com/Wixonic/Market"

commands:
    market:
        aliases: mk
        description: Shows the market interface
        usage: /<command>
        permission: market.access
        permission-message: You do not have permission to use this command.

permissions:
    market.access:
        description: Market access permissions
        default: true

    market.*:
        description: Wildcard permission
        default: op